name: Special Request Tech
favicon: null
layout_spectrum: 0.49026
typography_spectrum: 0.25661
title: 'NETWORKING & AERIAL PHOTOGRAPHY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76475020-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#006eb9'
    - '#cfe901'
    - '#bbd7e2'
    - '#368cc5'
  brandStrength: 0.0625
  lightness: 0.25
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
