analytics:
  google: UA-76475020-1
color:
  brandColors:
    - '#ffffff'
    - '#006eb9'
    - '#cfe901'
    - '#bbd7e2'
    - '#368cc5'
  brandStrength: 0.09375
  lightness: 0.25
  rhythmicContrast: 0.75
  saturation: 0.875
cta: {}
layout_spectrum: 0.596217
name: Special Request Tech
opengraph: {}
purpose: []
typography_spectrum: 0.103618
