name: Special Request Tech
favicon: null
layout_spectrum: 0.00487
typography_spectrum: 0.08788
title: 'NETWORKING & AERIAL PHOTOGRAPHY'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-76475020-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#151c14'
    - '#1279c6'
    - '#a9b9c8'
    - '#715e50'
  brandStrength: 0.8125
  lightness: 0.08989675459451973
  saturation: 0.875
  rhythmicContrast: 0.13736327667720616
purpose: []
